#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

volumes:
  orderer.example.com:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      #- ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peera/tls/ca.crt, /etc/hyperledger/crypto/peerb/tls/ca.crt, /etc/hyperledger/crypto/peerc/tls/ca.crt]
      #TODO remove?
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    working_dir: /etc/hyperledger
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ../artifacts/channel:/etc/hyperledger/configtx
        - ../artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/crypto/orderer
        - orderer.example.com:/var/hyperledger/production/orderer
#        - ../artifacts/crypto-config/peerOrganizations/a.example.com/peers/peer0.a.example.com/:/etc/hyperledger/crypto/peera
#        - ../artifacts/crypto-config/peerOrganizations/b.example.com/peers/peer0.b.example.com/:/etc/hyperledger/crypto/peerb
#        - ../artifacts/crypto-config/peerOrganizations/c.example.com/peers/peer0.c.example.com/:/etc/hyperledger/crypto/peerc

  cli.example.com:
    container_name: cli.example.com
    extends:
      file: base-intercept.yaml
      service: cli-base
    volumes:
        - ../artifacts/hosts/a/cli_hosts:/etc/hosts
#      - ../artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/etc/hyperledger/crypto/orderer/tls


  # simple http server to disseminate certificates
  www.example.com:
    extends:
      file: base-intercept.yaml
      service: www-base
    container_name: www.example.com
    ports:
      - 8080:80
